In [2]:
# # Module 2 – Data Analysis with Python

# ## Day 5 – NumPy and Pandas Fundamentals

# In this notebook, I will learn the fundamentals of NumPy and Pandas,
# which are widely used libraries for data analysis in Python.

In [3]:
import numpy as np
import pandas as pd

In [4]:
numbers = np.array([10,20,30,40,50])

print("Array", numbers)
print("Data Type: ", numbers.dtype)
print("Shape: ", numbers.shape)

Array [10 20 30 40 50]
Data Type:  int64
Shape:  (5,)


In [5]:
numbers = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(numbers))
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("Minimum:", np.min(numbers))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [6]:
marks = np.array([
    [80, 85, 90],
    [75, 88, 92],
    [90, 95, 89]
])

print(marks)
print("Shape:", marks.shape)

[[80 85 90]
 [75 88 92]
 [90 95 89]]
Shape: (3, 3)


In [7]:
marks = pd.Series([50, 89, 78, 99, 67])
print(marks)

0    50
1    89
2    78
3    99
4    67
dtype: int64


In [8]:
data = {
    "Name": ["Ali", "Vicky", "sweety", "kartiki", "Shrisha"],
    "Age": [20, 34, 22, 21, 23],
    "Marks": [80, 99, 78, 89, 87]

    }

df = pd.DataFrame(data)
df

,Name,Age,Marks
0,Ali,20,80
1,Vicky,34,99
2,sweety,22,78
3,kartiki,21,89
4,Shrisha,23,87


In [9]:
print("First rows:")
print(df.head())

print("\nColumns:")
print(df.columns)

print("\nShape:")
print(df.shape)

First rows:
      Name  Age  Marks
0      Ali   20     80
1    Vicky   34     99
2   sweety   22     78
3  kartiki   21     89
4  Shrisha   23     87

Columns:
Index(['Name', 'Age', 'Marks'], dtype='object')

Shape:
(5, 3)


In [10]:
print(df.describe())

             Age      Marks
count   5.000000   5.000000
mean   24.000000  86.600000
std     5.700877   8.324662
min    20.000000  78.000000
25%    21.000000  80.000000
50%    22.000000  87.000000
75%    23.000000  89.000000
max    34.000000  99.000000


In [ ]:
## Day 5 – Conclusion

# Today I learned the fundamentals of NumPy and Pandas.

# I practiced:
# - NumPy arrays
# - NumPy calculations
# - Pandas Series
# - Pandas DataFrames
# - Basic DataFrame operations
# - Descriptive statistics